SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BOARD_WIDTH = 800
BOARD_HEIGHT = 600

ASTEROID_MIN_RADIUS = 15
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 8
PLAYER_TURNING_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5

SCALE = SCREEN_HEIGHT / BOARD_HEIGHT

DEBUG = False

